[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "zarr-datafusion"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["datafusion>=43.0.0"]

[tool.maturin]
python-source = "python"
module-name = "zarr_datafusion._internal"
